export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_DONE = 'FETCH_ARTICLES_DONE';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_DONE = 'FETCH_ARTICLE_DONE';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_DONE = 'DELETE_ARTICLE_DONE';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_DONE = 'CREATE_ARTICLE_DONE';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';

