export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_DONE = 'FETCH_ARTICLES_DONE';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const FETCH_ARTICLE_DONE = 'FETCH_ARTICLE_DONE';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';
